version: '3.8'

services:
  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "8080:8080"
    restart: always
    environment:
      - PORT=8080
    networks:
      - barrank-network  # 👈 Asignamos la red al servicio

networks:
  barrank-network:        # 👈 Definimos o conectamos a la red
    external: true


